/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gallhp;

import Tpdahp.Tpdahp;
import Tpdohp.Tpdohp;
import Tpfahp.Tpfahp;
import Twfahp.Twfahp;
import edu.gatech.hp.HeatedPlateSimulator;
import java.awt.Cursor;
import javax.swing.SwingWorker;

/**
 *
 * @author jsoto
 */
public class Demo extends javax.swing.JFrame {

    SimulationTask worker;
    
    private class SimulationTask extends SwingWorker<Void, Void> {

        @Override
        protected Void doInBackground() throws Exception {
            
            // disable controls
            enableControls(false);
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
            // get input
            int d = Integer.parseInt(dField.getText());
            int l = Integer.parseInt(lField.getText());
            int t = Integer.parseInt(tField.getText());
            int r = Integer.parseInt(rField.getText());
            int b = Integer.parseInt(bField.getText());
            
            // reset results area
            resultsArea.setText("");
        
            // perform simulation
            HeatedPlateSimulator simulator = (HeatedPlateSimulator) selector.getSelectedItem();
            String result = simulator.execute(d, l, r, t, b);
        
            // publish results
            resultsArea.setText(result);
            
            enableControls(false);
            return null;
        }
        
        @Override
        public void done() {
            enableControls(true);
            setCursor(Cursor.getDefaultCursor());
        }
    }
    
    /**
     * Creates new form Demo
     */
    public Demo() {
        initComponents();
        loadSimulators();
        
        // TODO remove
        dField.setText("3");
        lField.setText("75");
        tField.setText("100");
        rField.setText("50");
        bField.setText("0");
    }
    
    /**
     * Loads the different HeatedPlateSimulator implementations to
     * the simulators list.
     */
    private void loadSimulators() {
        // add Tpdah
        Tpdahp tpdahp = new Tpdahp();
        selector.addItem(tpdahp);
        // add Tpdohp
        Tpdohp tpdohp = new Tpdohp();
        selector.addItem(tpdohp);        
        // add Tpfahp
        Tpfahp tpfahp = new Tpfahp();
        selector.addItem(tpfahp);        
        // add Twfahp
        Twfahp twfahp = new Twfahp();
        selector.addItem(twfahp);
    }
    
    /**
     * @return if the simulation input is valid
     */
    private boolean validateInput() {
        return true;
    }
    
    /**
     * Disable or enable controls
     * @param enable indicates if controls should be enabled or disabled
     */
    private void enableControls(boolean enable) {
        // diable inputs
        dField.setEnabled(enable);
        lField.setEnabled(enable);
        tField.setEnabled(enable);
        rField.setEnabled(enable);
        bField.setEnabled(enable);
        
        // disable buttons
        simulateButton.setEnabled(enable);
        
        // disable selector
        selector.setEnabled(enable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultsPanel = new javax.swing.JScrollPane();
        resultsArea = new javax.swing.JTextArea();
        dLabel = new javax.swing.JLabel();
        lLabel = new javax.swing.JLabel();
        tLabel = new javax.swing.JLabel();
        rLabel = new javax.swing.JLabel();
        bLabel = new javax.swing.JLabel();
        dField = new javax.swing.JTextField();
        lField = new javax.swing.JTextField();
        tField = new javax.swing.JTextField();
        rField = new javax.swing.JTextField();
        bField = new javax.swing.JTextField();
        selector = new javax.swing.JComboBox();
        simulateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultsArea.setEditable(false);
        resultsArea.setColumns(20);
        resultsArea.setRows(5);
        resultsPanel.setViewportView(resultsArea);

        dLabel.setText("d");

        lLabel.setText("l");

        tLabel.setText("t");

        rLabel.setText("r");

        bLabel.setText("b");

        dField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dFieldActionPerformed(evt);
            }
        });

        tField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFieldActionPerformed(evt);
            }
        });

        rField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rFieldActionPerformed(evt);
            }
        });

        simulateButton.setBackground(new java.awt.Color(42, 82, 229));
        simulateButton.setForeground(java.awt.Color.white);
        simulateButton.setText("Simulate");
        simulateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(228, 60, 60));
        cancelButton.setForeground(java.awt.Color.white);
        cancelButton.setText("Cancel");
        cancelButton.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dLabel)
                            .addComponent(lLabel)
                            .addComponent(tLabel)
                            .addComponent(rLabel)
                            .addComponent(bLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bField)
                            .addComponent(rField)
                            .addComponent(tField)
                            .addComponent(lField)
                            .addComponent(dField)))
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simulateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(selector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dLabel)
                            .addComponent(dField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lLabel)
                            .addComponent(lField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tLabel)
                            .addComponent(tField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rLabel)
                            .addComponent(rField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bLabel)
                            .addComponent(bField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(simulateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton)
                        .addGap(0, 172, Short.MAX_VALUE))
                    .addComponent(resultsPanel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dFieldActionPerformed

    private void rFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rFieldActionPerformed

    private void simulateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateButtonActionPerformed
        // TODO add your handling code here:
        if(!validateInput()) {
            return;
        }
        
        // execute simulation
        worker = new SimulationTask();
        worker.execute();
    }//GEN-LAST:event_simulateButtonActionPerformed

    private void tFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Demo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bField;
    private javax.swing.JLabel bLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField dField;
    private javax.swing.JLabel dLabel;
    private javax.swing.JTextField lField;
    private javax.swing.JLabel lLabel;
    private javax.swing.JTextField rField;
    private javax.swing.JLabel rLabel;
    private javax.swing.JTextArea resultsArea;
    private javax.swing.JScrollPane resultsPanel;
    private javax.swing.JComboBox selector;
    private javax.swing.JButton simulateButton;
    private javax.swing.JTextField tField;
    private javax.swing.JLabel tLabel;
    // End of variables declaration//GEN-END:variables
}
